### PR TITLE
changed icon color to blue

### PR DESCRIPTION
**Pull request by kingcritter**
I did a lot of hard work and changed the color of the icon. Please accept my humble pull request.

### CODE REVIEW

**Review by wesleyvankomen — COMMENTED** [review]
I'm curious what all the extra code is for if this commit is only changing a fill color.

**Comment by kingcritter** [comment]
Well, the original was from Google's Material design page, so they probably
tweak the designs for maximum efficiency.

**Comment by wesleyvankomen** [comment]
from https://material.io/ ?

**Comment by kingcritter** [comment]
Correct.

**Pull request merged**
